# Generated by Django 2.1 on 2018-09-16 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cmc', models.DecimalField(decimal_places=3, max_digits=15)),
                ('loyalty', models.CharField(max_length=10)),
                ('mana_cost', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('oracle_text', models.TextField()),
                ('power', models.CharField(max_length=10)),
                ('reserved', models.BooleanField(default=False)),
                ('toughness', models.CharField(max_length=10)),
                ('type_line', models.CharField(max_length=75)),
                ('artist', models.CharField(max_length=75)),
                ('collector_number', models.CharField(max_length=75)),
                ('flavor_text', models.TextField()),
                ('image', models.URLField()),
                ('set', models.CharField(max_length=3)),
                ('set_name', models.CharField(max_length=50)),
                ('rarity', models.CharField(choices=[('1', 'Common'), ('2', 'Uncommon'), ('3', 'Rare'), ('4', 'Mythic')], default='1', max_length=1)),
                ('frame', models.CharField(choices=[('1', '1993'), ('2', '1997'), ('3', '2003'), ('4', '2015'), ('F', 'Future')], default='4', max_length=1)),
                ('border_color', models.CharField(choices=[('B', 'Black'), ('N', 'Borderless'), ('G', 'Gold'), ('S', 'Silver'), ('W', 'White')], default='B', max_length=1)),
                ('layout', models.CharField(choices=[('NRML', 'Normal'), ('SPLT', 'Split'), ('FLIP', 'Flip'), ('TRFM', 'Transform'), ('MELD', 'Meld'), ('LVLR', 'Leveler'), ('SAGA', 'Saga'), ('PLNR', 'Planar'), ('SCHM', 'Scheme'), ('VGRD', 'Vanguard'), ('TOKN', 'Token'), ('DFTK', 'Double-Faced Token'), ('EMBL', 'Emblem'), ('AGMT', 'Augment'), ('HOST', 'Host')], default='NRML', max_length=4)),
            ],
        ),
    ]
