# Generated by Django 2.1 on 2018-09-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20180930_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='set',
            new_name='set_abbr',
        ),
    ]
