# Generated by Django 2.1 on 2018-09-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_auto_20180930_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.TextField(null=True),
        ),
    ]
