# Generated by Django 2.1 on 2018-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.CharField(max_length=4),
        ),
    ]
