# Generated by Django 2.1 on 2018-09-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_auto_20180930_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='loyalty',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
