# Generated by Django 2.1.1 on 2018-10-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
        ('builder', '0002_auto_20181021_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='data',
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='browse.Card'),
        ),
    ]
