# Generated by Django 2.1.1 on 2018-10-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
        ('builder', '0004_auto_20181027_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='art_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_card', to='browse.Card'),
        ),
    ]
