# Generated by Django 2.1.1 on 2018-11-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
        ('builder', '0005_deck_art_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideboardCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.Deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='sideboard_cards',
            field=models.ManyToManyField(related_name='sideboard_cards', through='builder.SideboardCard', to='browse.Card'),
        ),
    ]
