# Generated by Django 2.1.1 on 2018-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_auto_20181109_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='sideboard_card_count',
            field=models.IntegerField(default=0),
        ),
    ]
