# Generated by Django 2.1.1 on 2018-11-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_deck_sideboard_card_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='parent_id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
