# Generated by Django 2.1.1 on 2018-11-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_deck_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='is_commander',
            field=models.BooleanField(default=False),
        ),
    ]
